### PR TITLE
Update vouchers to use model interfaces

### PR DESCRIPTION
**Pull request by pdbreen**
* [x] Needs additional test coverage for voucher interface methods
* [x] Needs composer require of tagged tipoff/test-support

### CODE REVIEW

**Comment by pdbreen** [comment]
This is now good to go -- just needs the tagged version of tipoff/test-support.

**Comment by drewroberts** [comment]
Should we get it to green or merge with the failing tests?

**Comment by pdbreen** [comment]
Yeah -- i've added hooks to run psalm/phpunit locally, but not --prefer-lowest.  All set now.  Had to bump addresses so DB tables load.

**Review by drewroberts — APPROVED** [review]
Thank you! 🚛

**Pull request merged**
