### PR TITLE
Add helper to create cartItem from sellable voucher type

### PR DESCRIPTION
**Pull request by pdbreen**
Setup for easier inclusion in Nova purchasing tool.

@drewroberts - may want to consider whether or not staff-bookings package is limited to purchase of only bookings.  If yes, then there will likely need to be a staff-vouchers and staff-products package to allow staff purchase of vouchers and products, possibly with some shared code between them (though, not exactly sure how easy sharing a common base is within a nova tool).   

It could also be three different Nova tools (one for each sellable type), but all provided from by a single package.  Sharing components would definitely be possible with this approach, as well as catering the UI to the type of item being purchased.  Really just need a more inclusive repo name - like staff-purchasing or similar.

### CODE REVIEW

**Comment by drewroberts** [comment]
> It could also be three different Nova tools (one for each sellable type), but all provided from by a single package. Sharing components would definitely be possible with this approach, as well as catering the UI to the type of item being purchased. Really just need a more inclusive repo name - like staff-purchasing or similar.

I like this approach better than 3 additional packages. I would also lean towards adding the vouchers purchase nova tool for staff to this package.

I also like having a base staff checkout tool in the checkout package and having the ability for vouchers to be added to it like we do with the front-end implementation. Is that possible?

**Comment by pdbreen** [comment]
Vue supports dynamic components as well, but being its an internal / staff tool, not sure cart items will actually need display customization - the item description & price info may be sufficient.  But, yes - the cart display / code entry / purchase process would all use the same Vue components, supporting routes.  What may happen is the area beneath the cart changes to a paneled display with a panel each for bookings, vouchers and products - the panel content being geared towards selection & configuration of the sellable for cart addition.

**Comment by drewroberts** [comment]
I really like this approach. Let's do it!

**Review by drewroberts — APPROVED** [review]
Thank you! ⛳

**Pull request merged**
