### PR TITLE
Update to use existing Voucher implementation with latest Checkout interfaces

### PR DESCRIPTION
**Pull request by pdbreen**

### CODE REVIEW

**Comment by drewroberts** [comment]
We still have some issues with the User model and the current tests of this package.

**Comment by pdbreen** [comment]
@drewroberts should be ok now.

**Comment by pdbreen** [comment]
@drewroberts strike that and hold for a sec on this one -- looks like one more issue in ci/cd with email config
```
 1) Tipoff\Vouchers\Tests\Unit\Listeners\OrderCreatedListenerTest::cart_vouchers_are_redeemed
Swift_TransportException: Expected response code 250 but got code "550", with message "550 5.7.1 Relaying denied
"
```

**Comment by pdbreen** [comment]
@drewroberts  - ok, now its ok.  For real this time.

**Review by drewroberts — APPROVED** [review]
Thank you! :octocat:

**Pull request merged**
